title: Méthologie Scientifique
description: UE Transerve L1 - 2022-2023
markdown: kramdown
theme: jekyll-theme-dinky
footer_content: "© 2023 - Rohan Fossé"
favicon: vba.io

kramdown:
  parse_block_html: true
  parse_span_html: true
  toc_levels: 2..3
github:
  is_project_page: false