title: <a href="rohanfosse.github.io/l1-methodo">Méthologie Scientifique</a>
description: UE Transerve L1 - 2022-2023
markdown: kramdown
footer_content: "© 2023 - Rohan Fossé"

remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

kramdown:
  parse_block_html: true
  parse_span_html: true
  toc_levels: 2..3
github:
  is_project_page: false